### ISSUE TITLE
Skills data; JSON for skills nonexistent?

### ISSUE THREAD

**Issue by janat08** [nezroy/EVEoj#7]
Don't think you have skills in ur data

**Comment by nezroy** [comment]
Hmm... I'll take a look, it's been a while since I've done anything skill-related. I'm fuzzily recalling that skill requirements have to be parsed through the dgm tables (basically skill requirements show up as dogma effects/attrs on items, which have to be back-tracked through dogma tables to the associated skills), but I'll go through and verify whether it can actually be pulled with the current data.

**Comment by janat08** [comment]
So it's doable, and dogma is one of your libraries?

**Comment by janat08** [comment]
Just in case, there's no documentation for that thing.

**Comment by janat08** [comment]
Ugh lol I made sense of what you mean, kek dgm tables.
